version: '3.0'
services:
    coffeeshop:
      build: coffeeshop_app:latest
      ports:
        - "8089:8085"
      env_file:
        - config.env
      volumes:
        - go-modules:/go/pkg/mod
volumes:
  go-modules: